DemoWEB2/Models/ErrorViewModel.cs
namespace DemoWEB2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoWEB2/Models/Person.cs
namespace DemoWEB2.Models
{
    public class Person
    {
        public string Name { get; set; } = string.Empty;
        public int Age { get; set; }
        public string Location { get; set; }= string.Empty;
    }
}

DemoWEB2/Models/StudentInfo.cs
using Microsoft.AspNetCore.Mvc;

namespace DemoWEB2.Models
{
    public class StudentInfo
    {
        public string? Id { get; set; }
        public string? Name { get; set; }
        public double? Marks { get; set; }

        
        public StudentInfo()
        {
            Id = "CT01";
            Name = "Thanh Nam";
            Marks = 7.5;
        }
    }
}

DemoWEB2/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace DemoWEB2.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CalPage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add()
        {
            try
            {
                int num1 = Convert.ToInt32(Request.Form["SoA"].ToString());
                int num2 = Convert.ToInt32(Request.Form["SoB"].ToString());
                ViewBag.Result = (num1 + num2).ToString();
            }
            catch (Exception)
            {

                ViewBag.Result="Du lieu nhap sai";
            }
            return View("CalPage");
        }

        [HttpPost]
        public IActionResult Minus()
        {
            try
            {
                int num1 = Convert.ToInt32(Request.Form["SoA"].ToString());
                int num2 = Convert.ToInt32(Request.Form["SoB"].ToString());
                ViewBag.Result = (num1 - num2).ToString();
            }
            catch (Exception)
            {

                ViewBag.Result = "Du lieu nhap sai";
            }
            return View("CalPage");
        }

        [HttpPost]
        public IActionResult Multiply()
        {
            try
            {
                int num1 = Convert.ToInt32(Request.Form["SoA"].ToString());
                int num2 = Convert.ToInt32(Request.Form["SoB"].ToString());
                ViewBag.Result = (num1 * num2).ToString();
            }
            catch (Exception)
            {

                ViewBag.Result = "Du lieu nhap sai";
            }
            return View("CalPage");
        }

        [HttpPost]
        public IActionResult Divide()
        {
            try
            {
                int num1 = Convert.ToInt32(Request.Form["SoA"].ToString());
                int num2 = Convert.ToInt32(Request.Form["SoB"].ToString());
                ViewBag.Result = (num1 / num2).ToString();
            }
            catch (Exception)
            {

                ViewBag.Result = "Du lieu nhap sai";
            }
            return View("CalPage");
        }
    }
}

DemoWEB2/Controllers/FirstController.cs
using DemoWEB2.Models;
using Microsoft.AspNetCore.Mvc;

namespace DemoWEB2.Controllers
{
    public class FirstController : Controller
    {

        //List<Person> people = new List<Person>
        //{
        //    new Person {Name="ABC", Age=19, Location="Ho Chi Minh"},
        //    new Person {Name="DEF", Age=20, Location="Ha Noi"},
        //    new Person {Name="GHK", Age=21, Location="Da Nang"},

        //};

        public string Index()
        {
            return "Hello , day la ung dung MVC";
        }

        public IActionResult Hello()
        {
            ViewBag.Message = "ViewBag Message";
            return View();
        }

        public IActionResult Info()
        {
            Person person = new Person();
            person.Name = "Ho va Ten";
            person.Age = 18;
            person.Location = "Ho Chi Minh";

            return View(person);
        }

        public IActionResult List()
        {
            //List<Person> pers = new List<Person>()
            //Person[] pers = new Person[]
            var pers = new List<Person>()
            {
                new Person {Name="ABC", Age=19, Location="Ho Chi Minh"},
                new Person {Name="DEF", Age=20, Location="Ha Noi"},
                new Person {Name="GHK", Age=21, Location="Da Nang"}
            };
            return View(pers);
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }
        public IActionResult Delete()
        {
            return View();
        }
    }
}

DemoWEB2/Controllers/HomeController.cs
using DemoWEB2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoWEB2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult About()
        {
            return View();
        }
        [HttpPost]
        public IActionResult PrintMessage()
        {
            ViewBag.Name= Request.Form["Name"].ToString();
            ViewBag.Sex = Request.Form["Sex"].ToString();
            ViewBag.Address = Request.Form["Address"].ToString();
            return View("About");
        }
    }
}

DemoWEB2/Controllers/StudentController.cs
using DemoWEB2.Models;
using Microsoft.AspNetCore.Mvc;

namespace DemoWEB2.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            var students = new List<StudentInfo>()
            {
                new StudentInfo {Id = "CT01", Name = "Thanh Nam", Marks = 7.5},
                new StudentInfo {Id = "CT02", Name = "Thanh Hai", Marks = 6.5},
                new StudentInfo {Id = "CT03", Name = "Thanh Huong", Marks = 8.5},
                new StudentInfo {Id = "CT04", Name = "Ngoc Thach", Marks = 7.5},
                new StudentInfo {Id = "CT05", Name = "Thai Binh", Marks = 8.5}
            };
            //OR
            /*
             List<StudentInfo> students = new List<StudentInfo>()
             {
                new StudentInfo {Id = "CT01", Name = "Thanh Nam", Marks = 7.5},
                new StudentInfo {Id = "CT02", Name = "Thanh Hai", Marks = 6.5},
                new StudentInfo {Id = "CT03", Name = "Thanh Huong", Marks = 8.5},
                new StudentInfo {Id = "CT04", Name = "Ngoc Thach", Marks = 7.5},
                new StudentInfo {Id = "CT05", Name = "Thai Binh", Marks = 8.5}
            };
             */
            ViewBag.TotalStudents = students.Count();
            return View(students);
        }

        public IActionResult ViewModelView()
        {
            ViewBag.StudentInfo = new StudentInfo();
            return View();
        }

       

    }
}

DemoWEB2/Views/Calculator/CalPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "My Calculator Page";
}
<h1>My Calculator Page</h1>
<br/>
<form asp-controller="Calculator" method="post">
    Nhap so A: <input name="SoA" type="text" /><br /><br />
    Nhap so B: <input name="SoB" type="text" /><br /><br />

    <input type="submit" value="+" formaction="Add"/> &nbsp;&nbsp;&nbsp;
    <input type="submit" value="-" formaction="Minus" /> &nbsp;&nbsp;&nbsp;
    <input type="submit" value="x" formaction="Multiply" /> &nbsp;&nbsp;&nbsp;
    <input type="submit" value="/" formaction="Divide" /> &nbsp;&nbsp;&nbsp;

</form>

<h2 style="color:crimson;background-color:darksalmon;padding:10px">
    Ket Qua: @ViewBag.Result
</h2>

DemoWEB2/Views/First/Create.cshtml
@model DemoWEB2.Models.Person

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoWEB2/Views/First/Delete.cshtml
@model DemoWEB2.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DemoWEB2/Views/First/Details.cshtml
@model DemoWEB2.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

DemoWEB2/Views/First/Edit.cshtml
@model DemoWEB2.Models.Person

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoWEB2/Views/First/Hello.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Hello";
}
<h2>Xin chao, View action Hello </h2>
<h2>@ViewBag.Message</h2>

DemoWEB2/Views/First/Info.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Person
@{
    ViewData["Title"] = "Info";
}
<h2>Info</h2>
<p>Name: @Model.Name</p>
<p>Age: @Model.Age</p>
<p>location: @Model.Location</p>

DemoWEB2/Views/First/List.cshtml
@model IEnumerable<DemoWEB2.Models.Person>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

DemoWEB2/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"]= "Gioi thieu";
}
<h1>Gioi thieu</h1>

<form asp-controller="Home" asp-action="PrintMessage">
    <table>
        <tr>
            <td>Ho va Ten</td>
            <td><input name="Name" type="text"/></td>
        </tr>
        <tr>
            <td>Gioi tinh</td>
            <td><select name="Sex" type="text" >
                <option value="Nam">Nam</option>
                <option value="Nu">Nu</option>
            </select>
            </td>
        </tr>
        <tr>
            <td>Dia chi</td>
            <td><input name="Address" type="text" /></td>
        </tr>
        <tr>
            <td colspan="2"><input id="Submit" type="submit" value="Save Details"/></td>
        </tr>
    </table>
</form>
<br/>
<h2 style="background-color:burlywood; padding:10px">
    Ho va Ten: @ViewBag.Name
    <br/>
    Gioi ting: @ViewBag.Sex
    <br/>
    Dia chi: @ViewBag.Address
</h2>

DemoWEB2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DemoWEB2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoWEB2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoWEB2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoWEB2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="First" asp-action="Info">My Info</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="CalPage">Calculator</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="ViewModelView">ViewModelView</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DemoWEB2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DemoWEB2/Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<DemoWEB2.Models.StudentInfo>
@{
    ViewData["Title"] = "Ket qua sinh vien";
}
<h1>Ket qua sinh vien</h1>
<table class="table">
    <tr>
        <td>MSSV</td>
        <td>Ten</td>
        <td>Diem</td>
    </tr>


@foreach(var i in Model)
{
    <tr>
        <td>@i.Id</td>
        <td>@i.Name</td>
        <td>@i.Marks</td>
    </tr>
}
</table>

<label>Tong so sv: </label> @ViewBag.TotalStudents

DemoWEB2/Views/Student/ViewModelView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    StudentInfo students = ViewBag.StudentInfo;

    <p>MSSV: @students.Id </p>
    <p>Ten: @students.Name</p>
    <p>Diem: @students.Marks </p>

}